name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - production
      - development

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd python-app
          npm install

      - name: Create .env from GitHub secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > python-app/.env

      - name: Set Deployment Path
        run: echo "DEPLOY_PATH=/home/ubuntu/deploy/python-app" >> $GITHUB_ENV

      - name: Deploy Code
        run: |
          mkdir -p $DEPLOY_PATH
          cp -R ./python-app/* $DEPLOY_PATH
          cp python-app/.env $DEPLOY_PATH

      - name: Restart Application via PM2
        run: |
          cd $DEPLOY_PATH
          pm2 restart all || pm2 start index.js --name python-app
          pm2 save
