name: Python CI/CD

on:
  push:
    branches:
      - main
      - production
      - development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd python-app
          pip install -r requirements.txt

      - name: Create .env from GitHub secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > python-app/.env

      - name: Set Deployment Path
        run: echo "DEPLOY_PATH=/home/ubuntu/deploy/python-app" >> $GITHUB_ENV

      - name: Deploy Code
        run: |
          mkdir -p $DEPLOY_PATH
          cp -R ./python-app/* $DEPLOY_PATH
          cp python-app/.env $DEPLOY_PATH

      - name: Restart Python App with PM2
        run: |
          cd $DEPLOY_PATH
          pm2 restart python-app || pm2 start app.py --name python-app
          pm2 save
